### PR TITLE
#1 Add experimental Conda packaging

### PR DESCRIPTION
**Pull request by bergmanngabor**
Before merging, we should reconsider the branding / naming of packages.

There are two installable `conda` packages currently:  
- `iqs-twc-api` version 1.0.0 contributes the `iqs_client` namespace, which contains the generated Python client stub only
- `iqs-jupyter` version 0.0.1 contributes the `iqs_jupyter` namespace, which contains the manually written client extension code

I am open to applying a more sensible naming scheme.

C. f. conda package recipes:
https://github.com/IncQueryLabs/incquery-server-jupyter/blob/issues/1/releng/iqs-jupyter-packaging/conda/iqs-jupyter/meta.yaml
https://github.com/IncQueryLabs/incquery-server-jupyter/blob/issues/1/releng/iqs-jupyter-packaging/conda/iqs-twc-api/meta.yaml

### CODE REVIEW

**Comment by abelhegedus** [comment]
We should also consider the version numbers.

**Comment by bergmanngabor** [comment]
> We should also consider the version numbers.

Yeah, about that: ugh.
https://packaging.python.org/guides/single-sourcing-package-version/

**Comment by abelhegedus** [comment]
https://docs.conda.io/projects/conda-build/en/stable/concepts/package-naming-conv.html

I would suggest:
* `incqueryserver-api-python-client` with version that matches the version of IQS it was generated from (`0.10.0` soon)
* `incqueryserver-jupyter` with version that matches the python-client/IQS it works with
* We may think about separating the OSMC and MMS API parts from the IQS one with some arbitrary versions or simply use the version they are compatible with.

**Comment by bergmanngabor** [comment]
Your suggestions are for conda / pip package names. Are you fine with the Python namespaces / import module names?

> with version that matches the python-client/IQS it works with

Alternatively, it might make sense to keep it on a separate version track, as it mostly adds orthogonal functionality. But I can see the advantages of keeping the two versions in lockstep.

> We may think about separating the OSMC and MMS API parts from the IQS one with some arbitrary versions or simply use the version they are compatible with.

Will these correspond to different IQS distributions? Will there be multiple different OpenAPI .yaml specifications for the different configurations? If not, it would make sense to develop a single client that can connect to multiple IQS variants, though each would support a different API subset. (A list of installed capabilities may be provided at run-time, e.g. by the `​/server.info` API method.)

**Comment by abelhegedus** [comment]
> Your suggestions are for conda / pip package names. Are you fine with the Python namespaces / import module names?

They sound fine for now.

> Alternatively, it might make sense to keep it on a separate version track, as it mostly adds orthogonal functionality. But I can see the advantages of keeping the two versions in lockstep.

Some parts of the Jupyter integration deal with transforming and handling IQS data types, those parts will have to be synchronized with the version of IQS they work with, that's why I suggest the lockstep.

However, some other parts don't even use the IQS API and use the OSMC and MMS API directly. We could separate these as they have different "dependencies" both in Python import and used API version sense.

> Will these correspond to different IQS distributions? Will there be multiple different OpenAPI .yaml specifications for the different configurations? If not, it would make sense to develop a single client that can connect to multiple IQS variants, though each would support a different API subset. (A list of installed capabilities may be provided at run-time, e.g. by the `​/server.info` API method.)

Again, I meant the parts that are directly use OSMC or MMS API, not IQS related parts (such as the TWC revision widget that uses the IQS data to work).

**Comment by bergmanngabor** [comment]
I went with your suggestions. Package names and versions are updated, along with a restructuring of the repository.

README.md not yet updated, will come in a future commit.

**Pull request merged**
