### PR TITLE
#29 - publish conda packages

### LINKED ISSUE #29: Publish Conda packages
See e.g. ways to have them built on conda-forge.

See steps outlined here: https://github.com/IncQueryLabs/incquery-server-jupyter/issues/1#issuecomment-640207621

### PR DESCRIPTION
**Pull request by FuzesiMate**
fixes #29 
`incqueryserver-api-python-client 0.17.1` and `incqueryserver-jupyter 0.17.1` packages are now available as Conda packages.

### CODE REVIEW

**Review by abelhegedus — CHANGES_REQUESTED** [review]
I think it's enough to link to the feedstock repositories from the readme, all other packaging files can be removed from here.

**Review by bergmanngabor — APPROVED** [review]
Well, done, good to see that you managed to get conda-forge going!

I can't add much to the substance of the work, therefore only have cosmetic bikeshed comments:
- Can we collapse the badges / build reports so that they take up less space? For ex. the two conda packages each have a table with the same header, it looks like they could be merged.
- Maybe merge the build passing badge as a fifth column?
- It is redundant to have a header "PyPI packages" and then each badge state that they are indeed a PyPI package. Perhaps change the display text of these badges to the name of the package? Maybe even eliminate the subheadings  API client/ Jupyter extensions?
- Unrelated: the MyBinder badges could be moved under the "Try it first" heading

**Review by abelhegedus — APPROVED** [review]

**Comment by abelhegedus** [comment]
I agree with @bergmanngabor that the badge part should be more concise, but that can be done later.

**Comment by FuzesiMate** [comment]
> I agree with @bergmanngabor that the badge part should be more concise, but that can be done later.

It didn't takemuch time, so I cleaned up the badges a bit.

**Pull request merged**
